### PR TITLE
[4.0] Workflow help button

### PR DESCRIPTION
**Pull request by max123kl**
Pull Request für Issue #1142 

### Zusammenfassung der Änderungen
updated
administrator\language\de-DE\joomla.ini
api\language\de-DE\joomla.ini

### CODE REVIEW

**Review by tecpromotion — COMMENTED** [review]
@zero-24 Please check

I think here are still the old JHEP strings?
Would you please do a PR as a fix.

Siehe https://github.com/joomla/joomla-cms/blob/00429c85e698fbb74572261252bf924969a2610b/api/language/en-GB/joomla.ini#L674-L884

**Comment by zero-24** [comment]
Done: https://github.com/joomlagerman/joomla/pull/1345 But IIRC they are not used in the api app.

**Comment by tecpromotion** [comment]
obsolet with #1345 right @zero-24 ?

**Comment by zero-24** [comment]
Ja. mein PR ist eine 1:1 kopie vom aktuellen core.

**Comment by tecpromotion** [comment]
Danke @zero-24 und @max123kl

**Pull request closed without merging**
