### PR TITLE
[4.2] user profile dob field

### LINKED ISSUE #2496: [4.2] user profile dob field
New language relevant PR in upstream repo: https://github.com/joomla/joomla-cms/pull/38065 Here are the upstream changes: 
<details>
<summary>Click to expand the diff!</summary>

```diff
diff --git a/administrator/language/en-GB/plg_user_profile.ini b/administrator/language/en-GB/plg_user_profile.ini
index a2c2a57c1b37..9c752b56d7ad 100644
--- a/administrator/language/en-GB/plg_user_profile.ini
+++ b/administrator/language/en-GB/plg_user_profile.ini
@@ -12,6 +12,8 @@ PLG_USER_PROFILE_FIELD_ADDRESS1_LABEL="Address 1"
 PLG_USER_PROFILE_FIELD_ADDRESS2_LABEL="Address 2"
 PLG_USER_PROFILE_FIELD_CITY_LABEL="City"
 PLG_USER_PROFILE_FIELD_COUNTRY_LABEL="Country"
+PLG_USER_PROFILE_FIELD_DOB_DESCRIPTION="Year-Month-Day, eg 2019-01-27." ; Adapt to the format you entered in the 'DATE_FORMAT_CALENDAR_DATE'
+PLG_USER_PROFILE_FIELD_DOB_HINT="YYYY-MM-DD" ; Adapt to the format you entered in the 'DATE_FORMAT_CALENDAR_DATE'
 PLG_USER_PROFILE_FIELD_DOB_LABEL="Date of Birth"
 PLG_USER_PROFILE_FIELD_FAVORITE_BOOK_LABEL="Favourite Book"
 PLG_USER_PROFILE_FIELD_NAME_PROFILE_REQUIRE_USER="User profile fields for profile edit form"
@@ -27,5 +29,4 @@ PLG_USER_PROFILE_FILL_FIELD_DESC_SITE="If required, please fill this field."
 PLG_USER_PROFILE_OPTION_AGREE="Agree"
 PLG_USER_PROFILE_OPTION_DO_NOT_AGREE="I do not agree"
 PLG_USER_PROFILE_SLIDER_LABEL="User Profile"
-PLG_USER_PROFILE_SPACER_DOB="The date of birth entered should use the format Year-Month-Day, eg 2019-01-27." ; Adapt to the format you entered in the 'DATE_FORMAT_CALENDAR_DATE'
 PLG_USER_PROFILE_XML_DESCRIPTION="User Profile Plugin"
diff --git a/layouts/plugins/user/profile/fields/dob.php b/layouts/plugins/user/profile/fields/dob.php
deleted file mode 100644
index 2aa0f0e42994..000000000000
--- a/layouts/plugins/user/profile/fields/dob.php
+++ /dev/null
@@ -1,24 +0,0 @@
-<?php
-/**
- * @package     Joomla.Site
- * @subpackage  Layout
- *
- * @copyright   (C) 2014 Open Source Matters, Inc. <https://www.joomla.org>
- * @license     GNU General Public License version 2 or later; see LICENSE.txt
- */
-
-defined('_JEXEC') or die;
-
-extract($displayData);
-
-/**
- * Layout variables
- * -----------------
- * @var   string  $text  infotext to be displayed
- */
-
-// Closing the opening .control-group and .control-label div so we can add our info text on own line ?>
-</div></div>
-<div class="controls"><?php echo $text; ?></div>
-<?php // Creating new .control-group and .control-label for the actual field ?>
-<div class="control-group"><div class="control-label">
diff --git a/plugins/user/profile/forms/profile.xml b/plugins/user/profile/forms/profile.xml
index 38a1bfce5c5e..fa6d0a724ecc 100644
--- a/plugins/user/profile/forms/profile.xml
+++ b/plugins/user/profile/forms/profile.xml
@@ -89,9 +89,10 @@
 
 			<field
 				name="dob"
-				type="dob"
+				type="calendar"
 				label="PLG_USER_PROFILE_FIELD_DOB_LABEL"
-				info="PLG_USER_PROFILE_SPACER_DOB"
+				description="PLG_USER_PROFILE_FIELD_DOB_DESCRIPTION"
+				hint="PLG_USER_PROFILE_FIELD_DOB_HINT"
 				translateformat="true"
 				showtime="false"
 				filter="server_utc"
diff --git a/plugins/user/profile/src/Field/DobField.php b/plugins/user/profile/src/Field/DobField.php
deleted file mode 100644
index 9afcb398c949..000000000000
--- a/plugins/user/profile/src/Field/DobField.php
+++ /dev/null
@@ -1,67 +0,0 @@
-<?php
-/**
- * @package     Joomla.Plugin
- * @subpackage  User.profile
- *
- * @copyright   (C) 2014 Open Source Matters, Inc. <https://www.joomla.org>
- * @license     GNU General Public License version 2 or later; see LICENSE.txt
- */
-
-namespace Joomla\Plugin\User\Profile\Field;
-
-\defined('JPATH_PLATFORM') or die;
-
-use Joomla\CMS\Factory;
-use Joomla\CMS\Form\Field\CalendarField;
-use Joomla\CMS\Language\Text;
-use Joomla\CMS\Layout\FileLayout;
-
-/**
- * Provides input for "Date of Birth" field
- *
- * @package     Joomla.Plugin
- * @subpackage  User.profile
- * @since       3.3.7
- */
-class DobField extends CalendarField
-{
-	/**
-	 * The form field type.
-	 *
-	 * @var    string
-	 * @since  3.3.7
-	 */
-	protected $type = 'Dob';
-
-	/**
-	 * Method to get the field label markup.
-	 *
-	 * @return  string  The field label markup.
-	 *
-	 * @since   3.3.7
-	 */
-	protected function getLabel()
-	{
-		$label = parent::getLabel();
-
-		// Get the info text from the XML element, defaulting to empty.
-		$text  = $this->element['info'] ? (string) $this->element['info'] : '';
-		$text  = $this->translateLabel ? Text::_($text) : $text;
-
-		if ($text)
-		{
-			$app    = Factory::getApplication();
-			$view   = $app->input->getString('view', '');
-
-			// Only display the tip when editing profile
-			if ($view === 'registration' || $view === 'profile' || $app->isClient('administrator'))
-			{
-				$layout = new FileLayout('plugins.user.profile.fields.dob');
-				$info   = $layout->render(array('text' => $text));
-				$label  = $info . $label;
-			}
-		}
-
-		return $label;
-	}
-}

```
</details>

### PR DESCRIPTION
**Pull request by tecpromotion**
Pull Request für Issue #2496 .

### Zusammenfassung der Änderungen

add two new strings
translation

### Wo wird der Sprachstring angezeigt / Wie kann getestet werden

backend

### CODE REVIEW

**Review by zero-24 — COMMENTED** [review]
can we move the comments above the lines?

**Comment by tecpromotion** [comment]
> can we move the comments above the lines?

why?

**Comment by heelc29** [comment]
I think for crowdin it is necessary at the end of the line (https://github.com/joomla/joomla-cms/pull/34671)

> Basically comments are moved to the end of the line in the *.ini

image

**Review by heelc29 — APPROVED** [review]
image

**Pull request merged**
